// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	models "gophkeeper/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// NotesKeeper is an autogenerated mock type for the NotesKeeper type
type NotesKeeper struct {
	mock.Mock
}

// AddNote provides a mock function with given fields: title, body, key
func (_m *NotesKeeper) AddNote(title string, body string, key []byte) error {
	ret := _m.Called(title, body, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []byte) error); ok {
		r0 = rf(title, body, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckFile provides a mock function with given fields:
func (_m *NotesKeeper) CheckFile() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// DeleteNote provides a mock function with given fields: index
func (_m *NotesKeeper) DeleteNote(index int) error {
	ret := _m.Called(index)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(index)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Flush provides a mock function with given fields: hash
func (_m *NotesKeeper) Flush(hash []byte) error {
	ret := _m.Called(hash)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNote provides a mock function with given fields: index
func (_m *NotesKeeper) GetNote(index int) (models.Note, error) {
	ret := _m.Called(index)

	var r0 models.Note
	if rf, ok := ret.Get(0).(func(int) models.Note); ok {
		r0 = rf(index)
	} else {
		r0 = ret.Get(0).(models.Note)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(index)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotes provides a mock function with given fields: all
func (_m *NotesKeeper) GetNotes(all bool) []models.Note {
	ret := _m.Called(all)

	var r0 []models.Note
	if rf, ok := ret.Get(0).(func(bool) []models.Note); ok {
		r0 = rf(all)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Note)
		}
	}

	return r0
}

// GetNotesCount provides a mock function with given fields:
func (_m *NotesKeeper) GetNotesCount() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Load provides a mock function with given fields: hash
func (_m *NotesKeeper) Load(hash []byte) error {
	ret := _m.Called(hash)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
