// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	models "gophkeeper/pkg/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SyncClient is an autogenerated mock type for the SyncClient type
type SyncClient struct {
	mock.Mock
}

// SyncData provides a mock function with given fields: notes, lastSync
func (_m *SyncClient) SyncData(notes []models.Note, lastSync time.Time) ([]models.Note, time.Time, error) {
	ret := _m.Called(notes, lastSync)

	var r0 []models.Note
	if rf, ok := ret.Get(0).(func([]models.Note, time.Time) []models.Note); ok {
		r0 = rf(notes, lastSync)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Note)
		}
	}

	var r1 time.Time
	if rf, ok := ret.Get(1).(func([]models.Note, time.Time) time.Time); ok {
		r1 = rf(notes, lastSync)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func([]models.Note, time.Time) error); ok {
		r2 = rf(notes, lastSync)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
