// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeGophKeeperServer is an autogenerated mock type for the UnsafeGophKeeperServer type
type UnsafeGophKeeperServer struct {
	mock.Mock
}

// mustEmbedUnimplementedGophKeeperServer provides a mock function with given fields:
func (_m *UnsafeGophKeeperServer) mustEmbedUnimplementedGophKeeperServer() {
	_m.Called()
}
